name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./gradlew check nativeImage
    - name: Run Windows exe
      if: ${{ matrix.os == 'windows-latest' }}
      run: app\build\graal\hello-world.exe
    - name: Run binary
      if: ${{ matrix.os != 'windows-latest' }}
      run: app/build/graal/hello-world

  build-jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build
      run: ./gradlew check distTar distZip
