name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./gradlew check nativeImage
    - run: cp app/build/graal/hello-world* ./app-${{ matrix.os }}
      shell: bash
    - run: file ./app-${{ matrix.os }}
      shell: bash
    - run: ./app-${{ matrix.os }}
      shell: bash

  build-jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build
      run: ./gradlew check distTar distZip
